### ISSUE TITLE
Hershey bug

### ISSUE THREAD

**Issue by gisep** [evil-mad/EggBot#102]
Hi,
i'm finding problems in tracing a gcode text path with spaces using the "Hershey Text" extension to do the text and "J Tech Photonics Laser Tool" to trace it.

The same problem is described here:
https://bugs.launchpad.net/inkscape/+bug/1646595
where Mitch Bradley suggests this patch:
https://launchpadlibrarian.net/295778686/hershey.patch

But i don't know how to run it on Windows 10.

Can you help me?

thanks,
giuseppe

**Comment by oskay** [comment]
Use the current version.

**Comment by gisep** [comment]
Thank you buddy, i will try it soon :)😊
________________________________
Da: Windell Oskay <notifications@github.com>
Inviato: giovedì 5 luglio 2018 18:17
A: evil-mad/EggBot
Cc: gisep; Author
Oggetto: Re: [evil-mad/EggBot] Hershey bug (#102)


Use the current version.

**Comment by oskay** [comment]
The patch that you were describing was incorporated into the EggBot code here (but not yet in Inkscape) some time ago, so if you download the repository  and manually install the current versions of hershey.py, hershey.inx and hersheydata.py within your copy of Inkscape, you should be good to go.
