### ISSUE TITLE
Windows 10, extension not showing up in inkscape

### ISSUE THREAD

**Issue by bryanAtGreenagedevelopment** [evil-mad/EggBot#104]
Tried installing at C:\Users\<user>\AppData\Roaming\inkscape\extensions
Also attempted at C:\ProgramFiles\Inkscape\share\extensions
Neither lets inkscape list EggBot as an extension option in Inkscape
All installers exited without errors.

**Comment by oskay** [comment]
You haven't said what you actually tried to install in those locations, nor 
Please try running the EggBot 2.5.0 installer for Windows (EggBot_250A.exe from https://github.com/evil-mad/EggBot/releases/tag/v2.5.0).

Then, restart Inkscape.

**Comment by oskay** [comment]
Since there hasn't been any follow up, I'm closing this.
