### ISSUE TITLE
Inkscape hatch extension "hatch spacing" set to zero

### ISSUE THREAD

**Issue by wrexy1994** [evil-mad/EggBot#105]
I was just using your hatch extension, and found when the hatch spacing was set to zero, and live preview is selected, my computer froze.
I'm running Ubuntu 18.04, Inkscape 0.92.
Looking at the eggbot_hatch.py on line 1005, i += spacing, the while loop will never end. So I changed in eggbot_hatch.inx on line 29, min = "0.1".

**Comment by oskay** [comment]
Thank you; I've  set the minimum in the .inx file, but also edited the python code so that this issue will not occur even if the inx file is overridden.
