### ISSUE TITLE
S2 command doesn't wait the full delay before moving to the next command

### ISSUE THREAD

**Issue by nornagon** [evil-mad/EggBot#110]
I'm sending the following sequence of commands to my Axidraw (fw v2.5.3):

```
>EM,2,2
<OK
>S2,15700,4,734,67
<OK
>LM,0,80,27488,0,80,27488
<OK
>LM,97184014,80,-27488,97184014,80,-27488
<OK
>S2,17750,4,734,67
<OK
>LM,0,-80,27488,0,-80,27488
<OK
>LM,97184014,-80,-27488,97184014,-80,-27488
<OK
>EM,0,0
<OK
```

i.e. pen down w/ 67ms delay, then LM move, then pen back up with 67ms delay, then another LM move. The difference in pen positions is (17750 – 15700 = 2050) clocks, and the rate is 734 clocks per 24ms, so I'd expect the pen motion to complete at the same time that the delay expires (2050 / 734 * 24 = 67.03). However, I observe that the XY motors begin moving before the pen motion completes. Here's a slo-mo video taken at 240fps on an iPhone: https://i.imgur.com/k5psmdB.gifv (rightclick and select 'show controls' to step through carefully).

I note the first XY motion starting at frame 56 or so, and the pen motion completing at around frame 70. The 2nd XY motion starts at frame 140ish, and the 2nd pen motion completes at around frame 150ish. ~10 frames here is [10f] / [240f/s] = 42 ms.

I can work around this by adding 100ms to the `delay` parameter, sending `S2,17750,4,734,167` instead of `S2,17750,4,734,67` for example, but I'm not sure why that would be necessary.

Thoughts?

**Comment by nornagon** [comment]
Ah hm, perhaps it's because the servo's physical position is lagging behind where the firmware is telling it to be?

I did another experiment, setting the rate to 0 and the delay to 137, and I observed the total pen movement to take 116ms.

**Comment by oskay** [comment]
Yes, the servo control signal is the control signal sent to the servo motor. (It does take time after sending the signal for it to move to the commanded position. You can switch the control signal instantaneously, but that doesn't increase the speed of the motor itself.)

@EmbeddedMan The documentation for S2 (current firmware versions) say that the execution is immediate -- is this correct? Or is it added to the queue, as it seems to say in the description?

**Comment by EmbeddedMan** [comment]
The S2 command does go through the motion queue - it is not immediate. I can update the docs to be more clear on that point.

To be 100% accurate, only S2 moves are placed into the queue. If you send 0 as the first parameter (to shut down that servo channel) it will take effect immediately.

**Comment by EmbeddedMan** [comment]
Doc updated.

**Comment by oskay** [comment]
Can you please clarify out under exactly which circumstances cause it to be executed immediately instead of being added to the queue?

**Comment by EmbeddedMan** [comment]
Certainly. If the first parameter to an S2 command (<position>) is the value 0, then the command is executed immediately.  This is a special value which signals the EBB to turn off that servo channel, so no more pulses are sent. That action happens immediately, not as part of the motion queue. All other values produce an actual move, which does get added to the queue.

**Comment by oskay** [comment]
I just added some additional changes that specify this (at least for the current S2 version). If it was that way for the prior S2 as well, that should get updated also.

**Comment by EmbeddedMan** [comment]
Man, the stuff you learn about your own code when you need to write docs for it. :-)

It turns out I was not absolutely correct in the above statements. While the command S2,0 does in fact turn off an RC channel (whatever is assigned to RP0, which doesn't do you much good) you will normally use it with two parameters: S2,0,4 for example, if you wanted to turn off the RC servo channel assigned to the RP4 pin. I'll update the doc to make this clear. Sorry for the confusion.

**Comment by nornagon** [comment]
Closing this issue because my original question ("why are these physical movements overlapping?") has been resolved :)

**Comment by EmbeddedMan** [comment]
As a follow up - the EBB command documentation has now been updated to accurately reflect what happens when a value of 0 is used as the 'position' parameter in the S2 command, for both firmware prior to and after 2.2.0.

**Comment by oskay** [comment]
Great-- thank you both.
