### ISSUE TITLE
(FR) Dissable steppers at the end of a print

### ISSUE THREAD

**Issue by ithinkido** [evil-mad/EggBot#121]
I think it would be great to have the option to choose to automatically disable the steppers from Eggbot control at the end of a print. Leaving the steppers enabled is good for when you need to do a pen change for example, but if not,  then it would be a great if the steppers were disabled at the end of the print automatically. A stepper just enabled and not moving is the quickest way to get hot stepper motors and drivers, and I do sometimes forget to manually toggle the "raise pen, turn off motors" option after every print so having a checkbox option to do this automatically would be super

**Comment by oskay** [comment]
If your steppers are getting uncomfortably hot, you probably need to turn down the setpoint current. They should be able to run all day without overheating.

I'm not sure that an option like this is needed in general; I've never heard another request for something like this.
