### ISSUE TITLE
"Input sanitization" broke inkscape driver

### ISSUE THREAD

**Issue by colincross** [evil-mad/EggBot#133]
https://github.com/evil-mad/EggBot/commit/413729178dac13b28f0c1e3398c9fe265a08f172 sanitizes `self.options.tab` by removing leading and trailing quote characters, but the result is compared against constant strings that are all surrounded by quote characters.  That causes all operations in the inkscape driver to do nothing.

**Comment by oskay** [comment]
Good catch. But, there may be other things that are broken in the repository at present. I'd encourage you to use the release versions.
