### ISSUE TITLE
EBB "PG" (and "PC") command changes do not always take effect right away

### ISSUE THREAD

**Issue by EmbeddedMan** [evil-mad/EggBot#137]
A bug exists in EBB v2.6.5 and below where new pulse configure (PC) values sometimes take up to 64K milliseconds to take effect.

**Comment by EmbeddedMan** [comment]
The code for this fix was merged into the EBB firmware v2.7.0 version, along with updates to the release notes and EBB documentation related to this fix.

**Comment by oskay** [comment]
Looks like this can be closed as completed.
