### ISSUE TITLE
Boot up default for servo on B0 changed from firmware version 2.56 to 2.6+ 

### ISSUE THREAD

**Issue by cyclicredundancy** [evil-mad/EggBot#169]
I am using EBB with watercolor bot 1.0 (EBB board version 2.3) and while updating the EBB firmware noticed that the servo on B0 now boots up to a different pen position, pen up vs. pen down previously. And somehow on my board this causes my servo to continuously make a clicking sound. Not sure if the clicking sound is because of an issue with my servo or something in the firmware.
Edit: Forgot to add that please feel free to close this issue if this is clearly a problem with my servo.

**Comment by oskay** [comment]
The power on position is nominally "pen up", and has been (at least) from 2.5.5 to present. However, this is only a default position, not the actual machine-specific nor software-specific pen-up/pen-down positions. The exact setpoints for the power on pen-up and pen-down position did change in 2.6.0 (2018).

Part of the WCB 1.0 assembly process is calibrating the servo positions. If you're changing servo motors, changing software, or changing firmware, you likely need to calibrate the servo position again-- no two servos work exactly the same, and the different software and firmware versions have different setpoints as well.

As for your servo, it may be end of life, or it may be trying to move out of range.

**Comment by cyclicredundancy** [comment]
Thanks! Closing this as it is not related to EBB firmware.
