### ISSUE TITLE
Firmware support for LVFS

### ISSUE THREAD

**Issue by xsuchy** [evil-mad/EggBot#173]
Please add firmware for EggBot to LVFS https://fwupd.org/ This standard for updating firmware on Linuxes and Chromebooks.

**Comment by oskay** [comment]
The EBB (EggBot) firmware does not run linux or chrome; using an update system designed to update Linux and Chrome does not seem warranted, appropriate, or even necessarily possible.

Additionally, note that we do not have any current or planned support for using an EBB from the Chrome OS.
