### ISSUE TITLE
Add formal support for multiple motor resolutions

### ISSUE THREAD

**Issue by oskay** [evil-mad/EggBot#18]
All "stock" EggBot kits use a total of 3200 steps per revolution. Current versions have 200 step/revolution motors and 16X microstepping drivers. Some beta models had 400 step/rev motors and 8X microstepping drivers.  However, it is also possible to construct versions with
* 1600 steps/rev (e.g., with 8X drivers and the 200 step/rev motors), or
* 6400 steps/rev (e.g., with 16X drivers and the 400 step/rev motors). 

The software needs to know the number of steps per revolution in order to properly scale the motor motion to the standard template, as well as to know when it is safe to "wrap around" an object to save pen-up travel distance.

Ideally, we would like to natively support these configurations:
1600 step/rev
3200 step/rev (default)
6400 step/rev

**Comment by oskay** [comment]
We could use a beta tester for these features. Any volunteers?

**Comment by EmbeddedMan** [comment]
Windell,

I'd be happy to test it out for you.

*Brian
