### ISSUE TITLE
Additional quotes prevent Eggbot.effect() recognising menu tab operations

### ISSUE THREAD

**Issue by VikOlliver** [evil-mad/EggBot#187]
in eggbot.py circa line 
191: def effect(self):

the values in self.options.tab may have leading and following double quotes when used on Linux (Ubuntu 20.04+) which will prevent *any* option working when the [Apply] button is clicked.

I'm no python expert and there's probably a proper fix, but after 
        self.CheckSVGforEggbotData()

adding
        # Remove stray quotes from option - bug!!! Vik
        self.options.tab=self.options.tab.strip('"')

will make the tab options function again.

Using Python 2.7.18

**Comment by VikOlliver** [comment]
My bad, old version.

**Comment by oskay** [comment]
No worries; we appreciate bug reports.
