### ISSUE TITLE
Inkscape 1.2.2 not corresponds with EggBot_250A

### ISSUE THREAD

**Issue by ralfsoegel** [evil-mad/EggBot#197]
The EggBot_250A can't find the Inkscape installation.
Error message: inkscape not found. Please install Inkscape 0.91 (or newer) and try again.
It is a windows 10 machine.

**Comment by oskay** [comment]
Is there a specific reason that you need to run this very old (2015) version rather than the current software?

**Comment by ralfsoegel** [comment]
Hi, this version was the direct inscape link on Github. The EggBot_240A askes for the inkscape directory, not the _250A.Hmm... 

 
 
  Am Fr., Apr. 7, 2023 at 18:27 schrieb Windell ***@***.***>:   


Is there a specific reason that you need to run this very old (2015) version rather than the current software?

**Comment by ralfsoegel** [comment]
Yes my fault, the inkscape version is like in the title the 1.2.2.2022.

**Comment by oskay** [comment]
I really don't follow. Is there a reason that you need to use these very old versions of the EggBot software, rather than the current version?

**Comment by ralfsoegel** [comment]
No, this old version is not required, i was a little hopeful to get the Eggbot in motion with smaller software skips. 
The installation of Inkscape 0.92.4 is on the run after that it cames the r281 beside. I hope it will work tomorrow! ;-)

**Comment by oskay** [comment]
Since you are using Inkscape 1.2, I would suggest using the current software version, with installers at: https://wiki.evilmadscientist.com/Installing_software
