### ISSUE TITLE
Spiral Wrapped Text extension fails if text contains any markup entities

### ISSUE THREAD

**Issue by Yura80** [evil-mad/EggBot#43]
If text contains any '&' entity, such as `&amp;`, it produces the following error:

Traceback (most recent call last):
  File "eggbot_spiraltext.py", line 400, in <module>
    e.affect()
  File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line 268, in affect
    self.effect()
  File "eggbot_spiraltext.py", line 366, in effect
    markup = processMarkup( self.options.text, self.options.fontfamily )
  File "eggbot_spiraltext.py", line 216, in processMarkup
    if entity_refs.has_key[eref]:
TypeError: 'builtin_function_or_method' object is unsubscriptable

A small patch is necessary:

```
diff --git a/inkscape_contributed/eggbot_spiraltext.py b/inkscape_contributed/eggbot_spiraltext.py
index d453f3a..3a0fba2 100755
--- a/inkscape_contributed/eggbot_spiraltext.py
+++ b/inkscape_contributed/eggbot_spiraltext.py
@@ -213,7 +213,7 @@ def processMarkup( text, family='sans' ):
                        j = text.find( ';', i+1 )
                        if ( j != -1 ):
                                eref = text[i:j+1]
-                               if entity_refs.has_key[eref]:
+                               if entity_refs.has_key(eref):
                                        outstr += entity_refs[eref]
                                        i = j + 1
                                else:
```

**Comment by oskay** [comment]
Thank you!  Accepted, implemented and closed. :)
