### ISSUE TITLE
Finish EBB Firmware 2.4.0 release

### ISSUE THREAD

**Issue by oskay** [evil-mad/EggBot#48]
AxiDraw is currently shipping with the experimental EBB 2.4.0 firmware (adding the "AM" command), but this firmware does not have a binary release, currently. @EmbeddedMan, can you please wrap this one up?

**Comment by EmbeddedMan** [comment]
Yeah, whoops. My mistake. I will get the binary images posted shortly.
Thanks for the reminder-

**Comment by oskay** [comment]
Thanks!

**Comment by EmbeddedMan** [comment]
I rebuilt the binaries and they have now been pushed to this repo. There was no change to the hex file from the version that you have been using for AxiDraw. Please close if they look good.

**Comment by oskay** [comment]
Awesome-- thank you!
