### ISSUE TITLE
Very very minor issue: X-wrap will be ignored sometimes

### ISSUE THREAD

**Issue by ShelMi** [evil-mad/EggBot#49]
I mention this issue not because it's important, but because it involves pen up/down logic and I just want to check that there is no larger problem:

- When the pen is plotting at a distance from the document border - for example when doing a spiral-text plot - and
- if user presses the "pause" EBB button, and
- user then selects "Resume" tab, and
- user checks "Cancel and return home only"
then
- the self.bPenIsUp variable is uninitialized, and therefore
- plotLineAndTime() will ignore user's x-wrap selection, and
- will perform as many egg revolutions, at pen _down_ speed, as it takes to get back home.

A possible fix is shown in the attached image, but it may be that this is but a bandaid for a larger problem?  or a different problem??  Dunno, but just wanted to bring it up.

![fix undefined pen up-down after resume](https://cloud.githubusercontent.com/assets/16483308/16611729/211d3fc6-4331-11e6-90f8-d6ef2c4e491f.png)

**Comment by oskay** [comment]
I think that I remember seeing this once in practice, years ago, but had forgotten about it. Thanks for noticing; I'll take a look. :)

**Comment by oskay** [comment]
I've made the change that you suggest above. I think that this will fix the problems both with the speed and wrapping, since the wrap-around logic should automatically implement once we're in pen-up mode. Please give it a try.

**Comment by ShelMi** [comment]
OK, have tried it on my test file - works like a charm.  Not sure that it needs further testing, what do you think?

**Comment by oskay** [comment]
I think that's a wrap. :)
