### ISSUE TITLE
EBB docs: Add note to each command if it travels through FIFO or not

### ISSUE THREAD

**Issue by EmbeddedMan** [evil-mad/EggBot#65]

**Comment by oskay** [comment]
If I may suggest a style of adding this notation:

After the <code><b>Firmware Version:</b> [...]</code> line, add one of the following two lines:

<code><b> Execution:</b> Immediate </code> 
<code><b> Execution:</b> Added to FIFO motion queue </code>

**Comment by oskay** [comment]
Nice!
