### ISSUE TITLE
Question: the character is trembling

### ISSUE THREAD

**Issue by odasato** [evil-mad/EggBot#76]
Please, help me!

My name is odasato, Japanese.

I bought egg-bot several days ago.
But when it'll be tried out, the character is trembling like an attached picture.
Does the person who knows what causes have?

I feel the motor attached on the root of the arm with the pen to be vibrating.

I'm not good at English, so it takes time for an answer.

![dsc_8120](https://cloud.githubusercontent.com/assets/28254978/25577348/483c5406-2ea0-11e7-964d-a2463b42fec8.JPG)
I'll want to write "mangetsu"

**Comment by oskay** [comment]
This is not a software issue. It may be a problem with the physical machine, with the current setpoint on the motor controller, or something related. 

Check this guide for some suggestions: http://wiki.evilmadscientist.com/Eggbot_Quality_Troubleshooting
