### ISSUE TITLE
Request for info: AM Command

### ISSUE THREAD

**Issue by chrsmlls333** [evil-mad/EggBot#81]
What is the status of the AM command currently? I see in the release notes for 2.4.0:

> NOTE: AM command may not be quite 'right' yet. Although it has passed simple tests, it could not be made to reliably work from the Inkscape plugin, so it is not currently being used. It may have to change in future versions of this firmware.

And due to it not being documented in the [Command Reference](http://evil-mad.github.io/EggBot/ebb.html#EBB_Command_Reference), I assume its not production ready. May I ask what the holdups/errors were?

**Comment by oskay** [comment]
The documentation is technically there in the command reference, but it's commented out. We recommend the use of the new LM command instead.
