### ISSUE TITLE
EBB can't read high on PortB pin 7

### ISSUE THREAD

**Issue by EmbeddedMan** [evil-mad/EggBot#82]
If you send a "PI,B,7" it will always return 0 even if the pin is at 5V.

**Comment by oskay** [comment]
Is this still an issue? Might be good to patch it in the current round of revisions.

**Comment by EmbeddedMan** [comment]
Yes, it is still an issue. I will see if I can fix it in 2.5.4.

**Comment by EmbeddedMan** [comment]
Problem found, and now fixed. New v2.5.4 committed to EBB_Naming branch.
