### ISSUE TITLE
Unable to install Eggbot extensions on Mac OS10.12.6 with Inkscape 0.91 installed

### ISSUE THREAD

**Issue by staceybailey** [evil-mad/EggBot#89]
When using the installer on my mac, the installer will not progress beyond the destination selection, though I do have a later version of Inkscape installed.  Is this something you have encountered previously?  Any advice?

(Thanks in advance.)

![screen shot 2017-11-05 at 10 27 26 am](https://user-images.githubusercontent.com/19480393/32416241-5595c09e-c214-11e7-8769-b8771af9e7d2.png)

**Comment by oskay** [comment]
Please try following along with the current installation instructions. If you continue to have trouble, try a manual install or open a new ticket.
