### ISSUE TITLE
Dedicated repo for the EBB firmware only

### ISSUE THREAD

**Issue by ertdfgcvb** [evil-mad/EggBot#93]
EggBot and AxiDraw share the same firmware: a dedicated repo (without the drivers and plugins) could be more suitable…

**Comment by oskay** [comment]
Not a terrible idea, but I'm concerned that forking it off would lose our git history and issues. Additionally, we have a _lot_ of links out there pointing towards the documentation here. We'd need to keep the github.io page and structure in place for link forwarding.

**Comment by oskay** [comment]
I've added an EBB-Firmware label, that can at least label firmware issues.
